<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
#1st way of imputing 0 matrix
r1=int(input(print("enter number of row for matrics A"))) 
c1=int(input(print("enter number of column for matrics A")))
r2=int(input(print("enter number of row for matrics B")))
c2=int(input(print("enter number of column for matrics B")))
a=[]
c=[]
for i in range(r1):
  for j in range(c1):
       c.append(0)
  a.append(c)
  c=[]
print(a)


In [0]:
# 2nd way of imputing 0 matrix
A   = [[1,2],[3,4]]
B   = [[1,2,3,4,5],[5,6,7,8,9]]
r1=len(A) 
c1=len(A[0])
r2=len(B)
c2=len(B[0])
c=[]
d=[]
for i in range(r1):
  for j in range(c2):
       c.append(0)
  d.append(c)
  c=[]
print (d)
#Multiplication process
if (c1== r2):
  print("Multiplication is possible")
  for i in range(r1):
    for j in range(c2):
      for k in range(c1):
        c[i] [j]=c[i][j]+A[i][k]*B[k][j]
  print (c) 
else:
  print("Multiplication is not possible")

Multiplication is possible
[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    return(#multiplication_of_A_and_B)
    
matrix_mul(A, B)

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [0]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.
    #.
    return #selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

In [0]:
lst =[100,5]

In [0]:

def pick_a_number_from_list(A):
  import random
  A.sort(reverse=True)
  i=0
  j=0
  c=[]
  val=0
  d= len(A)
  for i in A:
    for j in range(d):
      c.insert(val,i)
      val += 1
    d = d- 1
  return random.choice(c)


In [0]:
def sampling_based_on_magnitued():
  number=[]
  for i in range(1,100):
    number.append(pick_a_number_from_list(lst))
  return print(number)



In [14]:

sampling_based_on_magnitued()

[100, 100, 5, 100, 100, 100, 5, 100, 100, 5, 5, 100, 100, 100, 100, 100, 100, 5, 100, 5, 100, 100, 100, 100, 100, 5, 100, 100, 5, 5, 100, 100, 5, 100, 5, 100, 5, 100, 100, 5, 100, 100, 5, 100, 5, 100, 100, 100, 5, 5, 100, 100, 100, 5, 100, 100, 5, 100, 5, 5, 5, 100, 100, 100, 100, 5, 5, 100, 5, 5, 5, 100, 100, 5, 100, 100, 100, 5, 100, 100, 5, 100, 5, 100, 100, 100, 100, 5, 5, 100, 100, 100, 100, 100, 100, 100, 100, 100, 5]


In [11]:
type(x)

NoneType

<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:

def replace_digits(a):
  import re
  c=""
  b=[]
  i=0
  j=0
  for i in range(len(a)):
    b.append(a[i])
  for j in range(len(b)):
    if b[j].isdigit()==True:
      c = c+"#"
  return c

In [0]:
String=str(input(print("Enter String")))
replace_digits(String)


Enter String
Noneabc


''

In [0]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    # 
    return() # modified string which is after replacing the # with digits

replace_digits(String)

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    top_5_students = # compute this
    # write code for computing top least 5 students
    least_5_students = # compute this
    # write code for computing top least 5 students
    students_within_25_and_75 = # compute this
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(# those values)

In [0]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

In [0]:
def display_dash_board(students, Marks):
  tt= sorted(Marks,reverse=True)
  lt= sorted(Marks,reverse=False)
  i=0
  v=0
  top_5_students=[]
  least_5_students=[]
  students_within_25_and_75=[]
  dict={}
  ts=[]
  ls =[]
  ps=[]
  for j in range(len(Marks)):
    dict[students[j]]= Marks[j]
  for i in range(5):
    ts.append(tt[i])
    ls.append(lt[i])
  for x in range(3,8):
    ps.append(tt[x])
  for l in range(5):
    a=[k for k,v in dict.items() if ts [l] == v ]
    b=[k for k,v in dict.items() if ls [l] == v ]
    c=[k for k,v in dict.items() if ps [l] == v ]
    top_5_students.append(a)
    least_5_students.append(b)
    students_within_25_and_75.append(c)
  return top_5_students, least_5_students,students_within_25_and_75

In [0]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(Students, Marks)

([['student8'], ['student10'], ['student2'], ['student5'], ['student7']],
 [['student3'], ['student4'], ['student9'], ['student6'], ['student1']],
 [['student5'], ['student7'], ['student1'], ['student6'], ['student9']])

In [0]:
ts

[98, 80, 78, 48, 47]

<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [0]:

import math
p=3
q=-4
r=[]
a=[]
b=[]
l=0
k=0
v=0
dict={}

S= [(1,2),(3,4),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,-1)]
for i in range(len(S)):
  r.append(math.acos(((S[i][0]*p)+(S[i][1]*q))/(math.sqrt((S[i][0]**2)+(S[i][1]**2))*(math.sqrt(p**2+q**2)))))
for j in range(len(S)):
  dict[r[j]]=S[j]
a=sorted(r)
for l in range(5):
  b.append([v for k,v in dict.items() if a[l]== k])


In [0]:
b

[[(6, -7)], [(1, -1)], [(6, 0)], [(-5, -8)], [(-1, -1)]]

In [0]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print() #print the returned values

<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [0]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print() # the returned value

In [0]:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
L=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

In [0]:
a=[]
r=[]
b=[]
d=[]
k=0
j=0
for i in range(len(L)):
  a.append(L[i].split("x"))
  a[i].extend(a[i][1].split("y"))
  del a[i][1]



In [0]:
e=[]
d=[]
k=0
for k in range(len(a)):
  r=[]
  b=[]
  for j in range(len(Red)):
    r.append ( (float(a[k][0]) * Red[j][0]) + ( float(a[k][1]) * Red[j][1] ) + float(a[k][2])  )
    b.append ( (float(a[k][0]) * Blue[j][0]) + ( float(a[0][1]) * Blue[j][1] ) + float(a[0][2])  )
  d.append(r)
  e.append(b) 
    

In [0]:
x=0
m=0
l=0
for m in range(len(a)):
  for l in range((len(d[0])-1)):
    if ((d[m][l]>0 and d[m][l+1]>0) or (d[m][l]<0 and d[m][l+1]<0)) and ((e[m][l]>0 and e[m][l+1]>0) or (e[m][l]<0 and e[m][l+1]<0)):
      x=0
    else:
      x=1
      break
  if x==0:
    print("{}    can divide red and blue".format(L[m]))
  else:
    print("{}    can not divide red and blue".format(L[m]))


1x+1y+0    can divide red and blue
1x-1y+0    can not divide red and blue
1x+0y-3    can not divide red and blue
0x+1y-0.5    can divide red and blue


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

In [0]:
def curve_smoothing(string):
  s1=string.replace("_","0")
  c=s1.split(",")
  a=list(map((lambda x:int(x) ),c))

  b=0
  l=0
  flag=0
  j=1
  for i in range(len(a)):
    if a[i]!=0:
      b=b+a[i]
      l=l+1
      d=b/l
      e=i
      flag +=1
      if flag==2:
        for k in range(l):
            a[e]=d
            e=e-1
            b=a[e+1]
            flag=0
            j=0

    else:
      l=l+1
      if i==0:
        flag+=1
      elif i == (len(a)-1):
        d=b/l
        e=i
        for k in range(l):
            a[e]=d
            e=e-1
      elif j==0:
        flag+=1
        l=2  
        j=1
        
                  
  return print (a)

In [0]:
S1= "_,_,_,24"
#Output1: 6,6,6,6

s2= "40,_,_,_,60"
#Output2: 20,20,20,20,20

s3= "80,_,_,_,_"
#Output3: 16,16,16,16,16

s4= "_,_,30,_,_,_,50,_,_"
#Output4: 10,10,12,12,12,12,4,4,4

In [27]:
#S1= "_,_,_,24"
#Output1: 6,6,6,6
smoothed_values= curve_smoothing(S1)
smoothed_values

[6.0, 6.0, 6.0, 6.0]


In [28]:
#s2= "40,_,_,_,60"
#Output2: 20,20,20,20,20
smoothed_values= curve_smoothing(s2)
smoothed_values

[20.0, 20.0, 20.0, 20.0, 20.0]


In [29]:
#s3= "80,_,_,_,_"
#Output3: 16,16,16,16,16
smoothed_values= curve_smoothing(s3)
smoothed_values

[16.0, 16.0, 16.0, 16.0, 16.0]


In [30]:
#s4= "_,_,30,_,_,_,50,_,_"
#Output4: 10,10,12,12,12,12,4,4,4
smoothed_values= curve_smoothing(s4)
smoothed_values

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]
compute_conditional_probabilites(A)

In [0]:
A =[["F1",'S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]


In [0]:
b=[]
for i  in range(len(A)):
  b.append(tuple((A[i])))

In [0]:
c=0
d=0
for i in range(len(b)):
  for j in range(len(b)):
    if b[i][1]==(b[j][1]):
      d += 1
  c=(b.count(b[i])/d)
  print("probability of{0}={1}   {2}".format(b[i],c,d))
  d=0
  
  

probability of('F1', 'S1')=0.25   4
probability of('F2', 'S2')=0.3333333333333333   3
probability of('F3', 'S3')=0.3333333333333333   3
probability of('F1', 'S2')=0.3333333333333333   3
probability of('F2', 'S3')=0.3333333333333333   3
probability of('F3', 'S2')=0.3333333333333333   3
probability of('F2', 'S1')=0.25   4
probability of('F4', 'S1')=0.25   4
probability of('F4', 'S3')=0.3333333333333333   3
probability of('F5', 'S1')=0.25   4


'S1'

In [0]:
for j in range(len(b)):
  str(ci)=[]

SyntaxError: ignored

<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(#the above values)

In [0]:
P1= "the first column F will contain only 5 uniques values"
P2= "the second column S will contain only 3 uniques values"

In [0]:

def string_features(S1, S2):
  a=set(S1.split(" "))
  b=set(S2.split(" "))
  return len(a.intersection(b)),a-b,b-a

In [0]:
e,d,f = string_features(P1, P2)
print("a. Number of common words between S1, S2:{0} \nb. Words in S1 but not in S2 {1} \nc. Words in S2 but not in S1{2}".format(e,d,f))


a. Number of common words between S1, S2:7 
b. Words in S1 but not in S2 {'F', '5', 'first'} 
c. Words in S2 but not in S1{'3', 'S', 'second'}


In [0]:
d

{'5', 'F', 'first'}


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(# the above loss)

In [0]:
def compute_log_loss(b):
  import math
  c=0
  for i in range(len(b)):
    c = c+ (((b[i][0]) * math.log10(b[i][1]))+ ((1-(b[i][0])) * math.log10(1-(b[i][1]))))
  a= ( -1/len(b) ) 
  d=a*c
  return d

In [0]:
b=[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(b)

In [0]:
loss

0.42430993457031635